version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    networks:
      - productionNetwork
    depends_on:
      - redis
      - loki
    environment:
      - DATABASE_URL=sqlite:///./currency_conversion.db
      - REDIS_HOST=http://redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - API_URL=
      - API_ACCESS_KEY=
      - LOKI_URL=http://localhost:3100
      - LOKI_USER=
      - LOKI_PASSWORD=

  redis:
    image: redis:7.2.4
    command: redis-server --appendonly yes
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - productionNetwork
  
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:10.4.2
    depends_on:
      - loki
    ports:
      - "3000:3000"

networks:
  productionNetwork:
    driver: bridge
