version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    networks:
      - productionNetwork
    depends_on:
      - redis
      - loki
    environment:
      - DATABASE_URL=sqlite:///./currency_conversion.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - API_URL=http://api.exchangeratesapi.io/v1/latest
      - API_ACCESS_KEY=ac4c7adf77fee2fd432497b1ea365014
      - LOKI_URL=http://loki:3100
      - LOKI_USER=admin
      - LOKI_PASSWORD=admin

  redis:
    image: redis:7.2.4
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - productionNetwork

  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    networks:
      - productionNetwork

  grafana:
    image: grafana/grafana:10.4.2
    depends_on:
      - loki
    ports:
      - "3000:3000"
    networks:
      - productionNetwork
    environment:
    - GF_SERVER_ROOT_URL=https://currency-converter-api-victor-soares-4de6f54a.koyeb.app/grafana/ # change this to `http://localhost:3000/grafana/` if you run local 
    - GF_SERVER_SERVE_FROM_SUB_PATH=true

  # specially because Koyeb just works with one http port exposed
  nginx:
    image: nginx:1.26.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - productionNetwork
    depends_on:
      - fastapi
      - grafana

networks:
  productionNetwork:
    driver: bridge
