version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    networks:
      - productionNetwork
    depends_on:
      - redis
    environment:
      - SERVER_HOST=http://fastapi
      - SERVER_PORT=8000
      - DATABASE_URL=sqlite:///../currency_conversion.db
      - REDIS_HOST=http://redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - API_URL=
      - API_ACCESS_KEY=

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - productionNetwork

networks:
  productionNetwork:
    driver: bridge
